language:
  - java
jdk:
  - openjdk6
before_install:
  - uname -a
  - if [ `uname -m` = x86_64 ]; then sudo apt-get update; fi
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - export TERM=dumb
  - wget http://services.gradle.org/distributions/gradle-1.8-bin.zip
  - unzip -qq gradle-1.8-bin.zip
  - export GRADLE_HOME=$PWD/gradle-1.8
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
  - wget http://dl.google.com/android/android-sdk_r22.0.5-linux.tgz
  - tar -zxf android-sdk_r22.0.5-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo yes | android update sdk -t tools,platform-tools,extra-android-support,extra-android-m2repository,android-18 --force --no-ui
  - wget http://dl.google.com/android/repository/build-tools_r18.0.1-linux.zip
  - mkdir -p $ANDROID_HOME/build-tools
  - unzip -qq build-tools_r18.0.1-linux.zip -d $ANDROID_HOME/build-tools/
  - mv $ANDROID_HOME/build-tools/android-4.3 $ANDROID_HOME/build-tools/18.0.1
  - find $ANDROID_HOME/build-tools
  - file $ANDROID_HOME/build-tools/18.0.1/aapt
